version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@qmx8x1i4lty0nir1_low?TNS_ADMIN=/app/Wallet_tienda
      - spring.datasource.username=ADMIN
      - spring.datasource.password=KpHhn6cg1ZWHs6
    restart: always